version: "3.4"
services:
  redis:
    image: redis
  mongo:
    image: mongo
  web:
    build:
      context: ./
      target: production
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
