version: "3.4"
services:
  redis:
    image: redis
    container_name: api_redis
  mongo:
    image: mongo
    container_name: api_mongo
  web:
    env_file:
      - .env
    build:
      context: ./
      target: base
    container_name: api_gateway
    volumes:
      - .:/usr/src/app
      - node_module:/usr/src/app/node_modules
    ports:
      - "3000:3000"
volumes:
  node_module:
