version: "3.4"
services:
  redis:
    image: redis
    container_name: api_redis_prod
  mongo:
    image: mongo
    container_name: api_mongo_prod
  web:
    env_file:
      - .env.production
    build:
      context: ./
      target: base
    container_name: api_gateway_production
    ports:
      - "8080:80"
